version: '3.1'

services:

  neo4j:
    image: neo4j:3.4.1
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]