version: '3.1'

services:

  neo4j:
    image: neo4j:3.4.1
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH

  api:
    image: todo-api
    ports:
      - 3000:3000
    environment:
      - NEO4J_AUTH